### ISSUE TITLE
Переписать `write_in_usr_db(email, psw)` как метод класса. 

### ISSUE THREAD

**Issue by Glaih** [Glaih/TODOEd#12]
По-моему, в будущем будет удобней использовать класс для работы с базой данных. Как думаешь?

**Comment by titov-rabota** [comment]
Да, беспорно.
Но с учетом того, что в планах есть SQLAlchemy, к этому вопросу надо вернуться в этой задаче https://github.com/Glaih/TODOEd/issues/4

**Comment by Glaih** [comment]
Я думаю, можно даже сразу после #4. Сначала разобраться с интеграцией для того, что есть. А потом уже переписать как класс с интеграцией. Так удобней будет?

**Comment by titov-rabota** [comment]
SQLAlchemy это совершенно иной подход, твой старый код будет не нужен, придется все переписать.
При этом будет разумнее использовать ООП, чем процедурный стиль.

**Comment by titov-rabota** [comment]
Если вопросов больше нет, то закрой этот issue

**Comment by Glaih** [comment]
Спасибо!
