### ISSUE TITLE
Добавление задачи

### ISSUE THREAD

**Issue by titov-rabota** [Glaih/TODOEd#14]
Эндпоинт для создания новой задачи. В запросе будет приходить: заголовок задачи, описание задачи.

Добавление задачи должно быть возможно только для авторизованных пользователей. 

Перед тем как начнёшь писать код, напиши пожалуйста в комментарии ниже план своих действий: какие изменения в базу ты планируешь внести, какие запросы принимать, какие тест кейсы. Какие ошибки и как ты планируешь обработать.

**Comment by Glaih** [comment]
1. Добавить таблицу "task"

**Comment by Glaih** [comment]
1. Добавить таблицу `task`

**Comment by Glaih** [comment]
### _Тест Кейсы:_
_Pre-Conditions:_
        Получить валидный access token для пользователя test@mail.ru.
1. Post запрос с JWT и данными задачи на защищенный эндпоинт:
    _Test Steps:_
         Отправить Post запрос включающий в себя JSON вида
        ![image](https://user-images.githubusercontent.com/68474306/110126111-23610900-7dd5-11eb-9aa9-9b9334676db7.png)
      _Expected:_
        Сервер отправляет ответ {"successful": "task added"} с кодом 200
2.   Post запрос с JWT и данными задачи исключая ключ `deadline` на защищенный эндпоинт:
    _Test Steps:_
         Отправить Post запрос включающий в себя JSON вида
         ![image](https://user-images.githubusercontent.com/68474306/110125829-ccf3ca80-7dd4-11eb-8b7a-9532b56ce4a8.png)
      _Expected:_
        Сервер отправляет ответ {"successful": "task added"} с кодом 200

**Comment by Glaih** [comment]
### _Предполагаемые ошибки:_
`KeyError`, `TypeError` - по аналогии с регистрацией через функцию в блюпринтах. Подумаю над чем-то более эффективном.
Так же в модели надо будет создать ограничение на количество символов в полях с выводом ошибки. Для почты это тоже верно. И посмотреть как SQLite реагирует на неверный формат даты, чтобы понять, как это обрабатывать.

**Comment by titov-rabota** [comment]
Какое у тебя получилось подробное и красивое описание.
Круто получилось, но давай немного скорректируем имена.
### Алгоритм действий:
1. Переименуй пожалуйста: `Todo -> Task`, `task_id -> id`, `task -> text`, `created -> created_at`
2. В JSON надо немного подправить имена. Давай сделаем так:
Мы хотим получить более универсальный формат, что бы реиспльзовать его в дальнейшем.
```json
{
    "access_token": "TOKEN",
    "data": {
        "title": "...",
        "text": "...",
        "deadline": "..."
    }
}
```
**Обрати, пожалуйста, внимание на часовой пояс в котором ты планируем получать дату.** 
Обычно дата в базе хранится в UTC, но приходящие данные могут быть в другом часовом поясе, незабудь включить его в формат даты.
3. Из JWT лучше бери `user_id`, он закодирован в токене и для его получения не надо делать запроса к базе.  И не стоит привязываться к почте, сейчас этот способ идентификации становится менее актуальным.
4. Сделай в `Task.deadline` значение по умолчанию None. И не забудь заполнить поле `created_at` при создании таски.
5. В качестве ответа верни пожалуйста json вида:
```json
{
    "data": {
        "id": "...",
        "created_at": "...",
        "title": "...",
        "text": "...",
        "deadline": "..."
    }
}
```


### Предполагаемые ошибки:
1. Ошибка авторизации: неверный токен, протухший токен
2. Ошибка валидации данных: недопустимая длинна текстовых полей, неверный формат даты, дата из прошлого.
3. Несуществующий пользователь: пользователя удалили в момент после проверки токена из запроса, но до добавления новой задачи.

**Comment by Glaih** [comment]
У меня `identity=mail` в коде, я так понимаю лучше поменять его на `identity=_id`
