### ISSUE TITLE
Рефакторинг регистрации

### ISSUE THREAD

**Issue by titov-rabota** [Glaih/TODOEd#17]
Посмотри, пожалуйста, код регистрации. Может быть у тебя есть предложения, как улучшить его читаемость?
Если да, то опиши их в комментарии ниже.

**Comment by Glaih** [comment]
В данный момент переделываю под алхимию, в `app.py` тоже немного изменится.

**Comment by titov-rabota** [comment]
Судя по всему эта задача потеряла актуальность.
Я ее закрываю
