### ISSUE TITLE
Перенести проверку на `KeyError` и `TypeError` из регулятора в модель, как метод класса.

### ISSUE THREAD

**Issue by Glaih** [Glaih/TODOEd#21]
![image](https://user-images.githubusercontent.com/68474306/109386550-68d09280-790c-11eb-82bd-efb69f4e3538.png)

Кусок выделенный на скриншоте перенести в класс `User`.

**Comment by titov-rabota** [comment]
Зависит от того какую проблему ты так пытаешься решить.
Данный фрагмент есть только в одном месте, т.е. кол-во кода от этого не уменьшится.
При этом это увеличит связность, вместо 2х аргументов: email, password, минимального набора данных, необходимого для логики регистрации, ты будешь передавать `request`, который содержит кучу мусора. И ты будешь вынужден создавать этот `request` каждый раз, когда потребуется создать пользователя, к примеру в тестах.

Если ты планируешь передавать словарь вида `{'email': 'test@gmail.com', 'password': 'qwerty'}, то это выглядит не намного лучше. Фактически ты так скрываешь данные.

На мой взгляд профита от переноса указаного блока кода не так много.
Если я что-то упускаю, напиши подробнее.

**Comment by Glaih** [comment]
a24f672 вот тут получается, что это кусок дважды используется - в registration и в `login`.

**Comment by titov-rabota** [comment]
На мой взгляд этот код не относит к классу пользователя, он относится к логике получения email, password из запроса. Пользователь не должен ничего знать об источнике своих данных.

Я вижу несколько вариантов:
1. Ты можешь сделать функцию `user_data_from_request(request)`, которая будет тебе возвращать email, password из запроса. Это потребует минимум кода и при необходимости эту функцию можно будет внести в какой-то класс.
2. Перейти на class base view (во фласке они называются [Plugable View](https://flask.palletsprojects.com/en/1.1.x/views/))
И вынести функционал получения данных пользователя в базовый класс или миксин.

С учетом того, что кода у тебя мало и логика достаточно проста, а композиция как правило лучше чем наследование я бы посоветовал способ 1. Просто вынеси код в функцию и реиспользуй ее.
